### ISSUE TITLE
ResponseError: illegal_argument_exception

### ISSUE THREAD

**Issue by shashidhar702** [Kickbykick/Elastic-Cloud#1]
hi @Kickbykick 
i got this error in functions console logs 
**ResponseError: illegal_argument_exception
    at IncomingMessage.response.on (/workspace/node_modules/@elastic/elasticsearch/lib/Transport.js:257:25)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)**

and my code is 

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { Client } = require('@elastic/elasticsearch')

admin.initializeApp(functions.config().firebase);

const env = functions.config();
const auth = {
  username: env.elasticsearch.username,
  password: env.elasticsearch.password,
};

const client = new Client({
    node: env.elasticsearch.url,
    auth: auth,
})


exports.createPost = functions.firestore
    .document('chores/{choreId}')
    .onCreate( async (snap, context) => {

      console.log(snap.data());
        await client.index({
            index: 'chores',
            type: '_doc',
            id: snap.id,
            body: snap.data()
        })
    });

exports.updatePost = functions.firestore
    .document('chores/{choreId}')
    .onUpdate( async (snap, context) => {
        await client.update({
            index: 'chores',
            type: '_doc',
            id: context.params.choreId,
            body: snap.after.data()
        })
    });

exports.deletePost = functions.firestore
    .document('chores/{choreId}')
    .onDelete( snap => {
        client.delete({
            index: 'chores',
            type: '_doc',
            id: snap.id,
        })
    });
```

@Kickbykick ### please help me in resolvig this issue

**Comment by Kickbykick** [comment]
I apologize for the late reply. 
Your code looks clean so far, I cannot really tell what is happening here.

Did you check your cloud functions log on firebase? It usually says what like of code caused the error. If you can get that to me, we can work on this error.

Also do you have a field in your chores collection that is "choreId". Just checking because it has to be right name and string case
